// Configuration des documents attendus par statut de commande
// Certains statuts nécessitent des documents/photos/liens à fournir

export interface StatusDocumentConfig {
  status: string;
  label: string;
  labelZh: string;
  requiredDocuments: DocumentRequirement[];
}

export interface DocumentRequirement {
  id: string;
  label: string;
  labelZh: string;
  type: 'image' | 'document' | 'url';
  description: string;
  descriptionZh: string;
  visibleToClient: boolean;
  autoGenerated?: boolean; // Pour les factures générées automatiquement
  multiple?: boolean; // Permet plusieurs fichiers
}

export interface UploadedStatusDocument {
  id: string;
  requirement_id: string;
  status: string;
  name: string;
  url: string;
  type: string;
  size?: number;
  uploaded_at: string;
  uploaded_by: string;
  visible_to_client: boolean;
}

// Configuration des documents par statut
export const ORDER_STATUS_DOCUMENTS: StatusDocumentConfig[] = [
  {
    status: 'deposit_paid',
    label: 'Acompte payé',
    labelZh: '定金已付',
    requiredDocuments: [],
  },
  {
    status: 'vehicle_locked',
    label: 'Véhicule bloqué',
    labelZh: '车辆已锁定',
    requiredDocuments: [
      {
        id: 'vehicle_photos',
        label: 'Photos du véhicule',
        labelZh: '车辆照片',
        type: 'image',
        description: 'Photos actuelles du véhicule bloqué',
        descriptionZh: '已锁定车辆的实际照片',
        visibleToClient: true,
        multiple: true,
      },
    ],
  },
  {
    status: 'inspection_sent',
    label: 'Inspection envoyée',
    labelZh: '检测已发送',
    requiredDocuments: [
      {
        id: 'inspection_report',
        label: 'Rapport d\'inspection',
        labelZh: '检测报告',
        type: 'document',
        description: 'Document ou photos du rapport d\'inspection',
        descriptionZh: '检测报告文件或照片',
        visibleToClient: true,
        multiple: true,
      },
    ],
  },
  {
    status: 'full_payment_received',
    label: 'Totalité du paiement reçu',
    labelZh: '全款已收',
    requiredDocuments: [
      {
        id: 'driveby_invoice',
        label: 'Facture Driveby',
        labelZh: 'Driveby发票',
        type: 'document',
        description: 'Facture d\'achat générée automatiquement',
        descriptionZh: '自动生成的购买发票',
        visibleToClient: true,
        autoGenerated: true,
      },
    ],
  },
  {
    status: 'vehicle_purchased',
    label: 'Véhicule acheté',
    labelZh: '车辆已购买',
    requiredDocuments: [
      {
        id: 'purchase_invoice',
        label: 'Facture d\'achat (Admin)',
        labelZh: '采购发票（管理员）',
        type: 'document',
        description: 'Facture d\'achat du véhicule - Usage interne',
        descriptionZh: '车辆采购发票 - 内部使用',
        visibleToClient: false,
      },
    ],
  },
  {
    status: 'vehicle_received',
    label: 'Réception véhicule',
    labelZh: '车辆已接收',
    requiredDocuments: [
      {
        id: 'reception_photos',
        label: 'Photos de réception',
        labelZh: '接收照片',
        type: 'image',
        description: 'Photos du véhicule à la réception - Usage interne',
        descriptionZh: '接收时的车辆照片 - 内部使用',
        visibleToClient: false,
        multiple: true,
      },
    ],
  },
  {
    status: 'export_customs',
    label: 'Douane export',
    labelZh: '出口清关',
    requiredDocuments: [
      {
        id: 'export_docs',
        label: 'Documents douane export',
        labelZh: '出口报关文件',
        type: 'document',
        description: 'Documents de dédouanement export - Usage interne',
        descriptionZh: '出口报关文件 - 内部使用',
        visibleToClient: false,
        multiple: true,
      },
    ],
  },
  {
    status: 'in_transit',
    label: 'En transit',
    labelZh: '运输中',
    requiredDocuments: [],
  },
  {
    status: 'at_port',
    label: 'Au port',
    labelZh: '在港口',
    requiredDocuments: [
      {
        id: 'container_seal',
        label: 'Photo du plomb',
        labelZh: '铅封照片',
        type: 'image',
        description: 'Photo du plomb du container',
        descriptionZh: '集装箱铅封照片',
        visibleToClient: true,
      },
      {
        id: 'loading_photos',
        label: 'Photos chargement',
        labelZh: '装柜照片',
        type: 'image',
        description: 'Photos du chargement dans le container',
        descriptionZh: '装入集装箱的照片',
        visibleToClient: true,
        multiple: true,
      },
    ],
  },
  {
    status: 'shipping',
    label: 'En mer',
    labelZh: '海运中',
    requiredDocuments: [
      {
        id: 'tracking_url',
        label: 'URL de suivi',
        labelZh: '跟踪链接',
        type: 'url',
        description: 'Lien de suivi du container',
        descriptionZh: '集装箱跟踪链接',
        visibleToClient: true,
      },
    ],
  },
  {
    status: 'documents_ready',
    label: 'Remise documentation',
    labelZh: '文件就绪',
    requiredDocuments: [
      {
        id: 'bill_of_lading',
        label: 'Bill of Lading (BL)',
        labelZh: '提单 (BL)',
        type: 'document',
        description: 'Connaissement maritime',
        descriptionZh: '海运提单',
        visibleToClient: true,
      },
      {
        id: 'packing_list',
        label: 'Packing List',
        labelZh: '装箱单',
        type: 'document',
        description: 'Liste de colisage',
        descriptionZh: '装箱清单',
        visibleToClient: true,
      },
      {
        id: 'release_doc',
        label: 'Document de relâche',
        labelZh: '放行文件',
        type: 'document',
        description: 'Document de mainlevée',
        descriptionZh: '放行单据',
        visibleToClient: true,
      },
      {
        id: 'other_docs',
        label: 'Autres documents',
        labelZh: '其他文件',
        type: 'document',
        description: 'Autres documents pertinents',
        descriptionZh: '其他相关文件',
        visibleToClient: true,
        multiple: true,
      },
    ],
  },
  {
    status: 'customs',
    label: 'En douane',
    labelZh: '进口清关中',
    requiredDocuments: [],
  },
  {
    status: 'ready_pickup',
    label: 'Prêt pour retrait',
    labelZh: '待提车',
    requiredDocuments: [],
  },
  {
    status: 'delivered',
    label: 'Livré',
    labelZh: '已交付',
    requiredDocuments: [],
  },
];

// Helper pour obtenir la config d'un statut
export function getStatusDocumentConfig(status: string): StatusDocumentConfig | undefined {
  return ORDER_STATUS_DOCUMENTS.find(s => s.status === status);
}

// Helper pour vérifier si un statut a des documents requis
export function statusHasRequiredDocuments(status: string): boolean {
  const config = getStatusDocumentConfig(status);
  return (config?.requiredDocuments.length || 0) > 0;
}

// Helper pour obtenir les documents manquants pour un statut
export function getMissingDocuments(
  status: string,
  uploadedDocuments: UploadedStatusDocument[]
): DocumentRequirement[] {
  const config = getStatusDocumentConfig(status);
  if (!config) return [];

  return config.requiredDocuments.filter(req => {
    const uploaded = uploadedDocuments.filter(doc => doc.requirement_id === req.id);
    return uploaded.length === 0;
  });
}

// Helper pour obtenir les documents uploadés pour un statut
export function getDocumentsForStatus(
  status: string,
  uploadedDocuments: UploadedStatusDocument[]
): UploadedStatusDocument[] {
  return uploadedDocuments.filter(doc => doc.status === status);
}

// Helper pour obtenir les documents visibles au client
export function getClientVisibleDocuments(
  uploadedDocuments: UploadedStatusDocument[]
): UploadedStatusDocument[] {
  return uploadedDocuments.filter(doc => doc.visible_to_client);
}

// Obtenir tous les statuts avec leurs documents requis (pour affichage admin/collaborator)
export function getAllStatusesWithDocuments(): StatusDocumentConfig[] {
  return ORDER_STATUS_DOCUMENTS.filter(s => s.requiredDocuments.length > 0);
}
